[tools]
node = "24"
pnpm = "latest"
ripgrep = "latest"
shellcheck = "latest"
zizmor = "latest"

[settings]
lockfile = true
minimum_release_age = "7d"
npm.package_manager = "pnpm"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]
# Skills https://github.com/vercel-labs/skills/blob/v1.5.16/README.md#environment-variables
DISABLE_TELEMETRY = "1"

[hooks.enter]
run = """
mise install --quiet
mise run pnpm-install
"""

[tasks.pnpm-install]
description = "Installs dependencies with pnpm"
quiet = true
run = "pnpm install --loglevel error"
sources = ["package.json", "pnpm-lock.yaml", "mise.toml"]
outputs = ["node_modules/.pnpm/lock.yaml"]
